### ISSUE TITLE
N6000-PL support?

### ISSUE THREAD

**Issue by sidsahay** [OFS/ofs-n6001#1]
Hi

Does this release work with N6000-PL cards as well? 

Not sure if this wording in the release ("If using the Intel FPGA SmartNIC N6001-PL Platform (SKU2) for evaluation of the OFS release [...]") implies N6000-PL (SKU1) functionality too. Would there be a different release for that?

Thanks
Sid

**Comment by cohensus** [comment]
Hi Sid,
The N6000-PL is a Gen4x16 card similar to N6001 but in the N6000 design the PCIe bus is bifurcated with x8 going to an Intel E810 NIC.  The current shell in the ofs-n6001 repo does not have this NIC support with bypass in the Ethernet, but you could use it as a starting point for your N6000 design.  If you are interested in the N6000 design, please contact ofs.marketing@intel.com.  Hope this answers your question.

**Comment by sidsahay** [comment]
Hi @cohensus, sorry, I'm a little confused here. Are you saying that we can use this release as a starting point for a N6000-PL design? We have a Silicom N6010 and want to try OFS on it, but it's a N6000-PL platform, not N6001-PL platform. i.e. there is no E810 NIC in our card.

**Comment by cohensus** [comment]
HI Sid, sorry to confuse you.  I've edited my previous comment where I had a typo.  If you have an N6010 card without E810 NIC then you can use the design in the repository labeled ofs-n6001 for your design.

**Comment by sidsahay** [comment]
Thanks! I'll give it a go.
