### ISSUE TITLE
function of vab_option_bits.bin

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs-n6001#4]
what is function vab_option_bits.bin

`https://github.com/OFS/ofs-n6001/blob/release/ofs-2023.1/syn/syn_top/vab_option_bits.bin`

 it is used by pfg files in `syn/syn_top/`. it is not explained in documentation
 like
 `https://github.com/OFS/ofs-n6001/blob/release/ofs-2023.1/syn/syn_top/ofs_top_pof.pfg`
 
 ```
     <raw_files>
        <raw_file type="HEX" id="Info_Factory_1">./factory_image_info.hex</raw_file>
        <raw_file type="HEX" id="Info_User_1">./user1_image_info.hex</raw_file>
        <raw_file type="HEX" id="Info_User_2">./user2_image_info.hex</raw_file>
        <raw_file type="RBF" id="VAB_Option_Bits_File">./vab_option_bits.bin</raw_file>
    </raw_files>
    <flash_devices>
        <flash_device type="CFI_2Gb" id="Flash_Device_1">
            <partition reserved="1" fixed_s_addr="0" s_addr="auto" e_addr="auto" fixed_e_addr="0" id="OPTIONS" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x00010000" e_addr="auto" fixed_e_addr="0" id="Option_Bits_VAB" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x00020000" e_addr="0x381F000" fixed_e_addr="0" id="Factory_Image" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x04000000" e_addr="0x77FF000" fixed_e_addr="0" id="User_Image_1" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF6000" e_addr="auto" fixed_e_addr="0" id="factory_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF7000" e_addr="auto" fixed_e_addr="0" id="user1_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF8000" e_addr="auto" fixed_e_addr="0" id="user2_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x08000000" e_addr="0xB7FF000" fixed_e_addr="0" id="User_Image_2" size="0"/>
        </flash_device>
    </flash_devices>
    <assignments>
        <assignment page="1" partition_id="User_Image_1">
            <bitstream_id>Bitstream_1</bitstream_id>
        </assignment>
        <assignment page="2" partition_id="User_Image_2">
            <bitstream_id>Bitstream_1</bitstream_id>
        </assignment>
        <assignment page="0" partition_id="Factory_Image">
            <bitstream_id>Bitstream_1</bitstream_id>
        </assignment>
        <assignment partition_id="factory_image_info">
            <raw_file_id>Info_Factory_1</raw_file_id>
        </assignment>
        <assignment partition_id="user1_image_info">
            <raw_file_id>Info_User_1</raw_file_id>
        </assignment>
        <assignment partition_id="user2_image_info">
            <raw_file_id>Info_User_2</raw_file_id>
        </assignment>
        <assignment partition_id="Option_Bits_VAB">
            <raw_file_id>VAB_Option_Bits_File</raw_file_id>
        </assignment>
 ```

**Comment by DigitalAce9** [comment]
The "vab_option_bits.bin" file was generated by the software guys: originally Bijapur Jyotsna.  I think the Matthew Gerlach also knows how this file was generated.  The hardware team just included it in the builds so that the resulting Flash Image contained the bits and the proper VAB/non-VAB software image.

**Comment by Jdavidbr-alt** [comment]
Hello

Can you take a look at the HPS documentation related to VAB flow, please let me know if you have any question

https://ofs.github.io/ofs-2023.2/hw/n6001/dev_guides/hps_dev/hps_developer_ug/#25-authorization

**Comment by umairsiddiqui-digitek** [comment]
Two issues:

1) I was looking into N6001 BMC CPLD document:

**Board Management Controller User Guide: Open FPGA Stack for Intel® Agilex® 7 FPGA**

this document has following table (complete table not shown due to NDA):

**Table 5-3** Agilex FPGA Flash Layout

| **Block Description** | **SPI Access** | **Nios® II Access** | **Size** | **Address** | **Comments** |
| --- | --- | --- | --- | --- | --- |
| PFL Option bits | R | R | 64 KB | 0x001.0000 - 001.FFFF | Option bits |
| Reserved | R | R | 64 KB | 0x000.0000 - 000.FFFF | Reserved |


however layout in FPGA Flash generation file **ofs_top_pof.pfg** in OFS FIM (this repo)

https://github.com/OFS/ofs-agx7-pcie-attach/blob/release/ofs-2023.2/syn/board/n6001/syn_top/ofs_top_pof.pfg

is different.  

```
    <flash_devices>
        <flash_device type="CFI_2Gb" id="Flash_Device_1">
            <partition reserved="1" fixed_s_addr="0" s_addr="auto" e_addr="auto" fixed_e_addr="0" id="OPTIONS" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x00010000" e_addr="auto" fixed_e_addr="0" id="Option_Bits_VAB" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x00020000" e_addr="0x381F000" fixed_e_addr="0" id="Factory_Image" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x04000000" e_addr="0x77FF000" fixed_e_addr="0" id="User_Image_1" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF6000" e_addr="auto" fixed_e_addr="0" id="factory_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF7000" e_addr="auto" fixed_e_addr="0" id="user1_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x07FF8000" e_addr="auto" fixed_e_addr="0" id="user2_image_info" size="0"/>
            <partition reserved="0" fixed_s_addr="0" s_addr="0x08000000" e_addr="0xB7FF000" fixed_e_addr="0" id="User_Image_2" size="0"/>
        </flash_device>
    </flash_devices>
```
**In PFG file(s) the PFL option bits at address 0x0, but according to user guide it should at 0x00010000** .  The BMC documentation don't mention the position of  **Option_Bits_VAB**, maybe it need to moved to 0x0? 


2) I couldn't find way to regenerate the **vab_option_bits.bin**
https://github.com/OFS/ofs-agx7-pcie-attach/blob/release/ofs-2023.2/syn/board/n6001/syn_top/vab_option_bits.bin

**Comment by sanjgan** [comment]
Hi,

1. The PFL Option bits in the user guide is the Option_Bits_VAB. In BMC, the PFL II core looks at the 'Option_Bits_VAB'  and not the 'OPTIONS'.

2. Please refer below for a flow to update option bits created by our teammate Berk Adanur
    
![Option_bits_flow](https://github.com/OFS/ofs-agx7-pcie-attach/assets/131715605/f9a3083b-7b97-4c94-a74a-3e72902aac27)
