### ISSUE TITLE
FIM Developer guide correction - IOFS_BUILD_ROOT

### ISSUE THREAD

**Issue by riteshbel** [OFS/ofs-n6001#7]
https://ofs.github.io/ofs-2023.2/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#1321-walkthrough-clone-fim-repository

mkdir OFS_BUILD_ROOT
cd IOFS_BUILD_ROOT
export IOFS_BUILD_ROOT=$PWD

to 

mkdir OFS_BUILD_ROOT
cd OFS_BUILD_ROOT
export OFS_BUILD_ROOT=$PWD

**Comment by cohensus** [comment]
Fixed
