### ISSUE TITLE
setup_ofs_platform_afu_bbb.sh (ofs_common) checkout the latest master of ofs_platform_afu_bbb  instead of specified tag ofs-2023.2-1 or ofs-2023.3-1-rc2

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs-n6001#9]
`ofs-common/scripts/common/syn/pim/setup_ofs_platform_afu_bbb.sh` script checkout the latest master of ofs_platform_afu_bbb 
(https://github.com/OFS/ofs-platform-afu-bbb)
instead of specified tag ofs-2023.2-1 or ofs-2023.3-1-rc2

as mentioned here
https://github.com/orgs/OFS/discussions/51

and 

https://github.com/orgs/OFS/discussions/44

https://github.com/OFS/ofs-fim-common/blob/93b6cb4bff66e83e3b157fe0e6b9bda93224e0eb/scripts/common/syn/pim/setup_ofs_platform_afu_bbb.sh#L47

**Comment by badanur** [comment]
There are two ways to work around this:

Scenario 1: Newly cloned ofs-agx7-pcie-attach repo, build script has not been run
- Set OFS_PLATFORM_AFU_BBB_REPO_BRANCH environment variable to the branch you would like to use.
- e.g. export OFS_PLATFORM_AFU_BBB_REPO_BRANCH="ofs-2023.3-1-rc2"
- Run build script

Scenario 2: Build script has already been run without setting OFS_PLATFORM_AFU_BBB_REPO_BRANCH
- Navigate to ofs-platform-afu-bbb directory
- cd $OFS_ROOTDIR/external/ofs-platform-afu-bbb
- Checkout desired branch
- e.g. git checkout ofs-2023.3-1-rc2

**Comment by badanur** [comment]
@umairsiddiqui-digitek Are you still experiencing build errors after resolving the python command issue?
